version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install twine
          command: |
            sudo pip install twine
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: setup pypi credentials
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to cheeseshop if a tag found
          command: |
            tag=`git tag --points-at HEAD`
            if [ $tag ]; then
              echo Uploading
              python -m twine upload dist/*
            fi

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only: development
  new_release:
    jobs:
      - test:
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - test
